In [1]:
import numpy as np
import sys

In [13]:
a = np.array([1,2,3], dtype='int16')
print(a)

[1 2 3]


In [27]:
b = np.array([[9.0, 8.0, 7.0], [6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [29]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])

In [30]:
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [40]:
output = np.ones((5,5))
#print(output)

z = np.zeros((3,3))
z[1,1] = 9
#print(z)

output[1:4, 1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [47]:
a = np.array([1,2,3])
b = a.copy()

In [48]:
print(b)

[1 2 3]


In [49]:
b[0] = 100

In [50]:
print(b)

[100   2   3]


In [51]:
print(a)

[1 2 3]


In [63]:
a = np.arange(1,31)
a = a.reshape(6,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [64]:
a[2:4,:2]

array([[11, 12],
       [16, 17]])

In [65]:
a[[0,1,2,3], [1,2,3,4]]

array([ 2,  8, 14, 20])

In [81]:
a[[[0,0],[4,4],[5,5]],[[3,4],[3,4],[3,4]]]

array([[ 4,  5],
       [24, 25],
       [29, 30]])

In [83]:
a[[0,4,5], 3:]

array([[ 4,  5],
       [24, 25],
       [29, 30]])