# NumPy exercises

We are going to practice NumPy skills and basic syntax.

We put here also some examples that were not in the tutorial on purpose. Try to use google and offial NumPy documentation to solve these exercises.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Create a null vector of size 10 (★☆☆)

In [2]:
null_vector = np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 3.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [9]:
null_vector[4] = 1
print(null_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 4.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [14]:
vector = np.arange(10,50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 5.  Reverse a vector (first element becomes last) (★☆☆)

In [20]:
reversed = vector[::-1]
print(reversed)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 6.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [22]:
a = np.arange(0,9)
a = a.reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 7. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [23]:
arr = np.array([1,2,0,0,4,0])

non_zero = np.nonzero(arr)

print(non_zero)

(array([0, 1, 4]),)


#### 8. Create a 3x3x3 array with random values (★☆☆)

In [36]:
arr = np.random.random((3,3,3))
print(arr)

[[[0.74261898 0.1439757  0.98675516]
  [0.40278968 0.604653   0.58805761]
  [0.72593196 0.08346585 0.15480032]]

 [[0.8757342  0.87382221 0.46394885]
  [0.5061296  0.09614662 0.07655489]
  [0.4776876  0.48525561 0.55913066]]

 [[0.03198552 0.90663512 0.73780589]
  [0.61210539 0.63632564 0.75407836]
  [0.21272836 0.08394524 0.93679004]]]


#### 9. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [55]:
arr = np.random.random((10,10))
print(arr)

min = np.min(arr)
max = np.max(arr)

print(f'Min: {min}')
print(f'Max: {max}')

[[0.76078976 0.02385401 0.04461185 0.9870472  0.76864389 0.22133358
  0.71054895 0.61209878 0.64794072 0.59436884]
 [0.20643836 0.48749903 0.24199827 0.67594897 0.96894127 0.38741154
  0.77929989 0.98912004 0.89125029 0.33616613]
 [0.57388924 0.18064488 0.23920836 0.67750695 0.70687748 0.91486353
  0.84160276 0.02358917 0.12629566 0.96195174]
 [0.01565066 0.85402656 0.64186504 0.27363199 0.2236529  0.45341289
  0.65247981 0.43997475 0.08359181 0.61596872]
 [0.21540729 0.4912678  0.36194527 0.74613393 0.16911637 0.66894759
  0.83459018 0.96225966 0.89736447 0.21972031]
 [0.04464024 0.39502689 0.13387329 0.61982516 0.80337616 0.24959413
  0.41475332 0.28415502 0.52876574 0.9069137 ]
 [0.49296861 0.42278912 0.90788146 0.37710571 0.86394272 0.02969972
  0.69433341 0.84565171 0.44671006 0.32191504]
 [0.61799152 0.98794236 0.35847428 0.80968835 0.343781   0.7841288
  0.80452458 0.4072012  0.71663709 0.18553462]
 [0.90647742 0.06656873 0.41206072 0.53025527 0.94189994 0.76321215
  0.14527506 

#### 10. Create a random vector of size 30 and find the mean value (★☆☆)

In [44]:
random_vector = np.random.rand(30)

mean = np.mean(random_vector)

print("Random Vector: ", random_vector)
print("Mean: ", mean)

Random Vector:  [0.16338385 0.50133338 0.63176015 0.03442974 0.67500022 0.02359379
 0.15675988 0.1375957  0.34450003 0.89725955 0.99866278 0.39751232
 0.02897635 0.37851221 0.32081466 0.28452986 0.98320715 0.84272822
 0.88432524 0.18520314 0.87299663 0.6113872  0.2649126  0.3578647
 0.9395399  0.26628379 0.67821354 0.06092443 0.16791334 0.84093775]
Mean:  0.4643687362086177


#### 11. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [49]:
arr = np.ones((3,3))

arr[1,1] = 0

print(arr)

[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]


In [50]:
# Define the size of the array
rows, cols = 5, 5  # You can adjust these values as needed

# Create an array of zeros
array = np.zeros((rows, cols))

# Set the border elements to 1
array[0, :] = 1  # Top border
array[-1, :] = 1  # Bottom border
array[:, 0] = 1  # Left border
array[:, -1] = 1  # Right border

print(array)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 12. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [57]:
arr = np.ones((5,5))


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

#### 13. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [58]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False

#### 14. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [64]:
matrix = np.zeros((5,5))

values = np.array([1,2,3,4])

matrix[np.arange(1,5), np.arange(0,4)] = values

matrix

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 4., 0.]])

#### 15. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [65]:
shape = (6, 7, 8)

# The target index (considering 0-based indexing, so 99 for the 100th element)
index = 99

# Use unravel_index
result = np.unravel_index(index, shape)

print(result)

(1, 5, 3)


In [72]:
arr = np.zeros((6,7,8))
arr

array([[[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.,

#### 16. Normalize a 5x5 random matrix (★☆☆)

In [74]:
matrix = np.random.random((5,5))

norm = np.linalg.norm(matrix)

norm_matrix = matrix / norm

print(norm_matrix)

[[0.05056037 0.07609161 0.02085781 0.24483016 0.15735428]
 [0.29893603 0.26639871 0.16818041 0.1600548  0.35039028]
 [0.08783753 0.03162341 0.10976266 0.27118178 0.01214061]
 [0.28076027 0.18094286 0.10941241 0.14586691 0.28444976]
 [0.28968326 0.03376103 0.3396388  0.22056059 0.01659638]]


#### 17. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [77]:
arr = np.array([2,4,6,8,10])
arr[(arr > 3) & (arr < 8)] *= -1

print(arr)

[ 2 -4 -6  8 10]


#### 18. How to round away from zero a float array ? (★☆☆)

In [78]:
def round_away_from_zero(arr):
    # Use np.where to choose the rounding function based on the sign of each element
    return np.where(arr > 0, np.ceil(arr), np.floor(arr))

# Example usage
float_array = np.array([1.2, -1.2, 2.5, -2.5, 0.1, -0.1])
rounded_array = round_away_from_zero(float_array)
print(rounded_array)

[ 2. -2.  3. -3.  1. -1.]


#### 19. Find common values between two arrays? (★☆☆)

In [80]:
arr1 = np.array([1,2,3,4,5,6,7,8,9])
arr2 = np.array([8,9,10,11,12])

arr_inter = np.intersect1d(arr1, arr2)

arr_inter

array([8, 9])

#### 20. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

#### 21. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [96]:
rng = np.random.default_rng()
rng = rng.integers(10, size=10)
rng

array([7, 5, 2, 0, 6, 0, 1, 2, 3, 5])

In [99]:
rng = np.arange(10)
rng

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 22. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [109]:
rng = np.random.default_rng()
rng = rng.random(10)
rng

array([0.44719913, 0.45601741, 0.67612108, 0.95018893, 0.95988792,
       0.92894507, 0.6128445 , 0.67072742, 0.35935747, 0.2109365 ])

#### 23. Create a random vector of size 10 and sort it (★★☆)

In [114]:
rng = np.random.default_rng()
rng = rng.integers(10, size=10)
sorted = np.sort(rng)
sorted

array([0, 1, 3, 3, 3, 4, 6, 6, 7, 7])

#### 24. Consider two random arrays A and B, check if they are equal (★★☆)

In [122]:
rng1 = rng = np.random.default_rng()
rng2 = rng.integers(10, size=10)

rng2 = rng = np.random.default_rng()
rng2 = rng.integers(10, size=10)

are_equal = np.array_equal(rng1, rng2)

print(are_equal)

False


#### 25. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [135]:
rng = rng = np.random.default_rng()
rng = rng.integers(10, size=10)

max_index = np.argmax(rng)
rng[max_index] = 0
rng

array([0, 1, 4, 1, 6, 7, 3, 1, 6, 2])

#### 26. Find the closest value to random element in a vector? (★★☆)

#### 27. Convert a float (32 bits) array into an integer (32 bits) in place?

#### 28. Sort an array by the nth column? (★★☆)

#### 29. Find if a given 2D array has null (empty) columns? (★★☆)

#### 30. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 31. Swap two rows of an array? (★★★)

#### 32. How to negate a boolean value inside an array? (★★★)

#### 33. Find the most frequent value in an array?

#### 34. Get the n largest values of an array (★★★)

#### 35. Extract unique rows from a two dimensional array? (★★★)